// Generated by scripts/gesetze.mjs, do not edit. Run `bun run gesetze`.
// Wording taken verbatim from the official XML of gesetze-im-internet.de.
// Gesetze genießen keinen urheberrechtlichen Schutz (§ 5 Abs. 1 UrhG).
export interface StatuteSegment {
  text: string;
  // Part of the Satz this page is about, emphasised whole. A Frist is never a
  // bare number lifted out of the sentence that qualifies it.
  mark?: boolean;
  // A cross-reference to another Paragraf of the same Gesetz, checked to exist
  // before it was written here.
  href?: string;
}

export interface StatuteQuote {
  enbez: string;
  titel: string;
  url: string;
  stand: string | null;
  // false when only some Absätze of the Paragraf are printed, so the page can
  // say it is an excerpt instead of implying it shows the whole thing.
  complete: boolean;
  absaetze: StatuteSegment[][];
}

export const STATUTE_QUOTES: Record<string, StatuteQuote> = {
  "arbeitsuchend-melden": {
    "enbez": "§ 38",
    "titel": "Rechte und Pflichten der Ausbildung- und Arbeitsuchenden",
    "url": "https://www.gesetze-im-internet.de/sgb_3/__38.html",
    "stand": "2026-07-29",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Personen, deren Ausbildungs- oder Arbeitsverhältnis endet, sind verpflichtet, sich spätestens drei Monate vor dessen Beendigung bei der Agentur für Arbeit unter Angabe der persönlichen Daten und des Beendigungszeitpunktes des Ausbildungs- oder Arbeitsverhältnisses arbeitsuchend zu melden.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Liegen zwischen der Kenntnis des Beendigungszeitpunktes und der Beendigung des Ausbildungs- oder Arbeitsverhältnisses weniger als drei Monate, haben sie sich innerhalb von drei Tagen nach Kenntnis des Beendigungszeitpunktes zu melden."
        },
        {
          "text": " "
        },
        {
          "text": "Die Pflicht zur Meldung besteht unabhängig davon, ob der Fortbestand des Ausbildungs- oder Arbeitsverhältnisses gerichtlich geltend gemacht oder vom Arbeitgeber in Aussicht gestellt wird."
        },
        {
          "text": " "
        },
        {
          "text": "Die Pflicht zur Meldung gilt nicht bei einem betrieblichen Ausbildungsverhältnis."
        }
      ]
    ]
  },
  "kuendigungsfrist-pruefen": {
    "enbez": "§ 622",
    "titel": "Kündigungsfristen bei Arbeitsverhältnissen",
    "url": "https://www.gesetze-im-internet.de/bgb/__622.html",
    "stand": "2026-07-31",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Das Arbeitsverhältnis eines Arbeiters oder eines Angestellten (Arbeitnehmers) kann mit einer Frist von vier Wochen zum Fünfzehnten oder zum Ende eines Kalendermonats gekündigt werden.",
          "mark": true
        }
      ],
      [
        {
          "text": "(3) "
        },
        {
          "text": "Während einer vereinbarten Probezeit, längstens für die Dauer von sechs Monaten, kann das Arbeitsverhältnis mit einer Frist von zwei Wochen gekündigt werden."
        }
      ],
      [
        {
          "text": "(4) "
        },
        {
          "text": "Von den Absätzen 1 bis 3 abweichende Regelungen können durch Tarifvertrag vereinbart werden."
        },
        {
          "text": " "
        },
        {
          "text": "Im Geltungsbereich eines solchen Tarifvertrags gelten die abweichenden tarifvertraglichen Bestimmungen zwischen nicht tarifgebundenen Arbeitgebern und Arbeitnehmern, wenn ihre Anwendung zwischen ihnen vereinbart ist."
        }
      ]
    ]
  },
  "wohnung-kuendigen": {
    "enbez": "§ 573c",
    "titel": "Fristen der ordentlichen Kündigung",
    "url": "https://www.gesetze-im-internet.de/bgb/__573c.html",
    "stand": "2026-07-31",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Die Kündigung ist spätestens am dritten Werktag eines Kalendermonats zum Ablauf des übernächsten Monats zulässig.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Die Kündigungsfrist für den Vermieter verlängert sich nach fünf und acht Jahren seit der Überlassung des Wohnraums um jeweils drei Monate."
        }
      ],
      [
        {
          "text": "(4) "
        },
        {
          "text": "Eine zum Nachteil des Mieters von Absatz 1 oder 3 abweichende Vereinbarung ist unwirksam."
        }
      ]
    ]
  },
  "kindergeld-beantragen": {
    "enbez": "§ 70",
    "titel": "Festsetzung und Zahlung des Kindergeldes",
    "url": "https://www.gesetze-im-internet.de/estg/__70.html",
    "stand": "2026-08-04",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Das Kindergeld nach "
        },
        {
          "text": "§ 62",
          "href": "https://www.gesetze-im-internet.de/estg/__62.html"
        },
        {
          "text": " wird von den Familienkassen durch Bescheid festgesetzt und ausgezahlt."
        },
        {
          "text": " "
        },
        {
          "text": "Die Auszahlung von festgesetztem Kindergeld erfolgt rückwirkend nur für die letzten sechs Monate vor Beginn des Monats, in dem der Antrag auf Kindergeld eingegangen ist.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Der Anspruch auf Kindergeld nach "
        },
        {
          "text": "§ 62",
          "href": "https://www.gesetze-im-internet.de/estg/__62.html"
        },
        {
          "text": " bleibt von dieser Auszahlungsbeschränkung unberührt."
        }
      ]
    ]
  },
  "internetanbieter-kuendigen-ummelden": {
    "enbez": "§ 60",
    "titel": "Umzug",
    "url": "https://www.gesetze-im-internet.de/tkg_2021/__60.html",
    "stand": "2026-06-30",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Wenn ein Verbraucher seinen Wohnsitz wechselt und seine Verträge weiterführen möchte, ist der Anbieter von öffentlich zugänglichen Telekommunikationsdiensten verpflichtet, die vertraglich geschuldete Leistung an dem neuen Wohnsitz des Verbrauchers ohne Änderung der vereinbarten Vertragslaufzeit und der sonstigen Vertragsinhalte zu erbringen, soweit er diese dort anbietet."
        },
        {
          "text": " "
        },
        {
          "text": "Der Anbieter kann ein angemessenes Entgelt für den durch den Umzug entstandenen Aufwand verlangen, das jedoch nicht höher sein darf als das für die Schaltung eines Neuanschlusses vorgesehene Entgelt."
        }
      ],
      [
        {
          "text": "(2) "
        },
        {
          "text": "Wird die vertraglich geschuldete Leistung am neuen Wohnsitz nicht angeboten, kann der Verbraucher den Vertrag unter Einhaltung einer Kündigungsfrist von einem Monat kündigen.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Die Kündigung kann mit Wirkung zum Zeitpunkt des Auszugs oder mit Wirkung zu einem späteren Zeitpunkt erklärt werden."
        }
      ]
    ]
  },
  "geburtsanzeige-standesamt": {
    "enbez": "§ 18",
    "titel": "Anzeige",
    "url": "https://www.gesetze-im-internet.de/pstg/__18.html",
    "stand": "2026-08-06",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Die Geburt eines Kindes ist dem Standesamt, in dessen Zuständigkeitsbereich es geboren ist, binnen einer Woche anzuzeigen, und zwar 1. von den in ",
          "mark": true
        },
        {
          "text": "§ 19",
          "href": "https://www.gesetze-im-internet.de/pstg/__19.html",
          "mark": true
        },
        {
          "text": " Satz 1 genannten Personen mündlich oder schriftlich, oder 2. von den in ",
          "mark": true
        },
        {
          "text": "§ 20",
          "href": "https://www.gesetze-im-internet.de/pstg/__20.html",
          "mark": true
        },
        {
          "text": " Satz 1 und 2 genannten Einrichtungen schriftlich.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Ist ein Kind tot geboren, so muss die Anzeige spätestens am dritten auf die Geburt folgenden Werktag erstattet werden."
        },
        {
          "text": " "
        },
        {
          "text": "In den Fällen des Satzes 1 Nummer 1 haben die anzeigenden Personen die Geburt des Kindes glaubhaft zu machen."
        }
      ]
    ]
  },
  "elterngeld-beantragen": {
    "enbez": "§ 7",
    "titel": "Antragstellung",
    "url": "https://www.gesetze-im-internet.de/beeg/__7.html",
    "stand": "2026-05-06",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Elterngeld ist schriftlich zu beantragen."
        },
        {
          "text": " "
        },
        {
          "text": "Es wird rückwirkend nur für die letzten drei Lebensmonate vor Beginn des Lebensmonats geleistet, in dem der Antrag auf Elterngeld eingegangen ist.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Im Antrag ist anzugeben, für welche Lebensmonate Basiselterngeld, für welche Lebensmonate Elterngeld Plus oder für welche Lebensmonate Partnerschaftsbonus beantragt wird."
        }
      ]
    ]
  },
  "kfz-ummeldung": {
    "enbez": "§ 15",
    "titel": "Mitteilungspflichten bei Änderungen",
    "url": "https://www.gesetze-im-internet.de/fzv_2023/__15.html",
    "stand": "2026-07-17",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(4) "
        },
        {
          "text": "Verlegt der Halter seinen Wohnsitz oder Sitz in einen anderen Zulassungsbezirk, hat er unverzüglich 1. bei der für den neuen Wohnsitz oder Sitz zuständigen Zulassungsbehörde die Zuteilung eines neuen Kennzeichens, einer neuen Zulassungsbescheinigung Teil I und die Änderung der Angaben in der Zulassungsbescheinigung Teil II zu beantragen oder 2. der für den neuen Wohnsitz oder Sitz zuständigen Zulassungsbehörde mitzuteilen, dass das bisherige Kennzeichen weitergeführt werden soll, und die Zulassungsbescheinigung Teil I zur Änderung vorzulegen."
        },
        {
          "text": " "
        },
        {
          "text": "Kommt der Halter diesen Pflichten nicht nach, kann die zuständige Zulassungsbehörde für die Zeit bis zur Erfüllung der Pflichten den Betrieb des Fahrzeuges auf öffentlichen Straßen untersagen."
        },
        {
          "text": " "
        },
        {
          "text": "Der Halter darf die Inbetriebsetzung eines Fahrzeuges, dessen Betrieb nach Satz 2 untersagt ist, nicht anordnen oder zulassen."
        },
        {
          "text": " "
        },
        {
          "text": "Im Fall des Satzes 1 Nummer 1 hat die für den neuen Wohnsitz oder Sitz zuständige Zulassungsbehörde nach Vorlage der Zulassungsbescheinigung und der bisherigen Kennzeichenschilder zur Entstempelung dem Fahrzeug ein neues Kennzeichen zuzuteilen."
        },
        {
          "text": " "
        },
        {
          "text": "Im Fall des Satzes 1 Nummer 2 hat die für den neuen Wohnsitz oder Sitz zuständige Zulassungsbehörde die Zulassungsbescheinigung Teil I zu ändern."
        },
        {
          "text": " "
        },
        {
          "text": "Absatz 1 Satz 1 Nummer 1 bleibt unberührt."
        },
        {
          "text": " "
        },
        {
          "text": "Kommt der Halter seinen Pflichten nach Satz 1 trotz Anordnung nach Satz 2 nicht nach, kann die zuständige Zulassungsbehörde die Zulassungsbescheinigung im Verkehrsblatt mit einer Frist von vier Wochen zur Vorlage bei ihr aufbieten."
        },
        {
          "text": " "
        },
        {
          "text": "Mit erfolglosem Ablauf des Aufgebots endet die Zulassung des Fahrzeuges."
        }
      ]
    ]
  },
  "ummeldung-einwohnermeldeamt": {
    "enbez": "§ 17",
    "titel": "Anmeldung, Abmeldung",
    "url": "https://www.gesetze-im-internet.de/bmg/__17.html",
    "stand": "2026-08-06",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(1) "
        },
        {
          "text": "Wer eine Wohnung bezieht, hat sich innerhalb von zwei Wochen nach dem Einzug bei der Meldebehörde anzumelden.",
          "mark": true
        }
      ],
      [
        {
          "text": "(2) "
        },
        {
          "text": "Wer aus einer Wohnung auszieht und keine neue Wohnung im Inland bezieht, hat sich innerhalb von zwei Wochen nach dem Auszug bei der Meldebehörde abzumelden."
        },
        {
          "text": " "
        },
        {
          "text": "Eine Abmeldung ist frühestens eine Woche vor Auszug möglich; die Fortschreibung des Melderegisters erfolgt zum Datum des Auszugs."
        }
      ]
    ]
  },
  "steuererklaerung-abgeben": {
    "enbez": "§ 149",
    "titel": "Abgabe der Steuererklärungen",
    "url": "https://www.gesetze-im-internet.de/ao_1977/__149.html",
    "stand": "2026-08-12",
    "complete": false,
    "absaetze": [
      [
        {
          "text": "(2) "
        },
        {
          "text": "Soweit die Steuergesetze nichts anderes bestimmen, sind Steuererklärungen, die sich auf ein Kalenderjahr oder auf einen gesetzlich bestimmten Zeitpunkt beziehen, spätestens sieben Monate nach Ablauf des Kalenderjahres oder sieben Monate nach dem gesetzlich bestimmten Zeitpunkt abzugeben.",
          "mark": true
        },
        {
          "text": " "
        },
        {
          "text": "Bei Steuerpflichtigen, die den Gewinn aus Land- und Forstwirtschaft nach einem vom Kalenderjahr abweichenden Wirtschaftsjahr ermitteln, endet die Frist nicht vor Ablauf des siebten Monats, der auf den Schluss des in dem Kalenderjahr begonnenen Wirtschaftsjahres folgt."
        }
      ]
    ]
  }
};
