// Regenerates lib/holidays-de-data.ts, the German holiday table the browser
// reads. Runs as part of `bun run build`, so the years never go stale.
//
// Everything comes from date-holidays, the same source the Feiertage pages
// declare. The point of the table is only to keep that library, and the rules
// of every other country in it, out of the page bundle.
import { writeFileSync } from "node:fs";
import Holidays from "date-holidays";

const STATES = [
  "BW", "BY", "BE", "BB", "HB", "HH", "HE", "MV",
  "NI", "NW", "RP", "SL", "SN", "ST", "SH", "TH",
];

// A plan reaches at most a year past its anchor, and loadHolidays always asks
// for the year after the one it needs.
const from = new Date().getFullYear() - 1;
const years = Array.from({ length: 5 }, (_, i) => from + i);

// "" is the plan without a picked Ort: the nationwide holidays, no state.
const regions = ["", ...STATES];

const table = {};
for (const region of regions) {
  const h = new Holidays("DE", region, { types: ["public"] });
  const byYear = {};
  for (const year of years)
    byYear[year] = h
      .getHolidays(year)
      .filter((d) => d.type === "public")
      .map((d) => [d.date.slice(0, 10), d.name]);
  table[region || "DE"] = byYear;
}

const body = `// Generated by scripts/feiertage.mjs, do not edit.
// German public holidays per Bundesland, ${years[0]} to ${years[years.length - 1]}.
export const HOLIDAYS_DE: Record<
  string,
  Record<string, [date: string, name: string][]>
> = ${JSON.stringify(table)};
`;
writeFileSync("lib/holidays-de-data.ts", body);
const count = Object.values(table).reduce(
  (n, y) => n + Object.values(y).reduce((m, d) => m + d.length, 0),
  0,
);
console.error(`${count} holidays, ${(body.length / 1024).toFixed(1)} KiB`);
