// Regenerates lib/schulferien-data.ts from data/schulferien/*/data.yaml.
//
// The planner is the only consumer left: it warns when a Termin lands in the
// Ferien and draws them as a band on the timeline. Both want the same handful
// of date ranges per Bundesland, so they read a table out of the bundle rather
// than fetching an endpoint per region.
//
// Runs as part of `bun run build`, and reads only local yaml, so a build never
// waits on a network.
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { load } from "js-yaml";

const DIR = "data/schulferien";
const OUT = "lib/schulferien-data.ts";

const table = {};
let count = 0;
for (const code of readdirSync(DIR).filter((name) => {
  if (name.startsWith("_")) return false;
  return statSync(join(DIR, name)).isDirectory();
})) {
  const doc = load(readFileSync(join(DIR, code, "data.yaml"), "utf-8"));
  const windows = (doc.windows ?? [])
    .map((w) => [w.from, w.to, w.name ?? "Schulferien"])
    .sort((a, b) => a[0].localeCompare(b[0]));
  // Keyed the way the Ort picker names a Bundesland, so no consumer has to
  // remember which case the folder happened to use.
  table[code.toUpperCase()] = windows;
  count += windows.length;
}

const body = `// Generated by scripts/schulferien.mjs, do not edit.
// Schulferien per Bundesland, from the KMK dates in data/schulferien.
export const SCHULFERIEN: Record<
  string,
  [from: string, to: string, name: string][]
> = ${JSON.stringify(table)};
`;
writeFileSync(OUT, body);
console.error(
  `${count} Ferien in ${Object.keys(table).length} Bundesländer, ${(body.length / 1024).toFixed(1)} KiB`,
);
